
db:
  image: postgres
  volumes:
    - ./db/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
  ports:
    - "5400:5432"
  environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
