
db:
  image: postgres
  volumes:
    - ./data/db:/var/lib/postgresql/data
    - ./db/create_tables.sql:/docker-entrypoint-initdb.d
  environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
